sudo: required
language: generic

services:
   - docker

before_install:
   - docker build -t swintonp/react-test -f ./client/Dockerfile.dev ./client

script:
   - docker run -e CI=true swintonp/react-test npm test 

after_success:
   - docker build -t swintonp/multi-client ./client
   - docker build -t swintonp/multi-nginx ./nginx
   - docker build -t swintonp/multi-server ./server
   - docker build -t swintonp/multi-worker ./worker
   #Login to the docker CLI; first make sure to create the env variables in Travis-CI
   - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
   # Take the docker build images and push them to docker hub
   - docker push swintonp/multi-client
   - docker push swintonp/multi-nginx
   - docker push swintonp/multi-server
   - docker push swintonp/multi-worker
 
 deploy:
   provider: elasticbeanstalk
   region: 'us-east-2'
   app: 'multi-docker'
   env: 'MultiDocker-env'
   bucket_name: 'elasticbeanstalk-us-east-2-281400176519'
   bucket_path: 'docker-multi'
   on:
     branch: master
   access_key_id: $AWS_ACCESS_KEY
   secret_access_key:
      secure: $AWS_SECRET_KEY